/* eslint-disable */
export default {
  data: [{
    type: 'gif',
    id: '11fucLQCTOdvBS',
    slug: 'cat-car-wtf-11fucLQCTOdvBS',
    url: 'http:\/\/giphy.com\/gifs\/cat-car-wtf-11fucLQCTOdvBS',
    bitly_gif_url: 'http:\/\/gph.is\/1sCaI2c',
    bitly_url: 'http:\/\/gph.is\/1sCaI2c',
    embed_url: 'http:\/\/giphy.com\/embed\/11fucLQCTOdvBS',
    username: '',
    source: 'http:\/\/gifs.tastefullyoffensive.com\/post\/66799339242',
    rating: 'g',
    content_url: '',
    source_tld: 'gifs.tastefullyoffensive.com',
    source_post_url: 'http:\/\/gifs.tastefullyoffensive.com\/post\/66799339242',
    is_indexable: 0,
    import_datetime: '2016-06-13 15:15:32',
    trending_datetime: '2017-02-14 18:10:34',
    images: {
      fixed_height: {
        url: 'https:\/\/media2.giphy.com\/media\/11fucLQCTOdvBS\/200.gif',
        width: '286',
        height: '200',
        size: '243500',
        mp4: 'https:\/\/media2.giphy.com\/media\/11fucLQCTOdvBS\/200.mp4',
        mp4_size: '18200',
        webp: 'http:\/\/media2.giphy.com\/media\/11fucLQCTOdvBS\/200.webp',
        webp_size: '101194',
      },
      fixed_height_still: {
        url: 'https:\/\/media2.giphy.com\/media\/11fucLQCTOdvBS\/200_s.gif',
        width: '286',
        height: '200',
      },
      fixed_height_downsampled: {
        url: 'https:\/\/media2.giphy.com\/media\/11fucLQCTOdvBS\/200_d.gif',
        width: '286',
        height: '200',
        size: '109211',
        webp: 'http:\/\/media2.giphy.com\/media\/11fucLQCTOdvBS\/200_d.webp',
        webp_size: '42592',
      },
      fixed_width: {
        url: 'https:\/\/media2.giphy.com\/media\/11fucLQCTOdvBS\/200w.gif',
        width: '200',
        height: '140',
        size: '129571',
        mp4: 'https:\/\/media2.giphy.com\/media\/11fucLQCTOdvBS\/200w.mp4',
        mp4_size: '12425',
        webp: 'http:\/\/media2.giphy.com\/media\/11fucLQCTOdvBS\/200w.webp',
        webp_size: '64130',
      },
      fixed_width_still: {
        url: 'https:\/\/media2.giphy.com\/media\/11fucLQCTOdvBS\/200w_s.gif',
        width: '200',
        height: '140',
      },
      fixed_width_downsampled: {
        url: 'https:\/\/media2.giphy.com\/media\/11fucLQCTOdvBS\/200w_d.gif',
        width: '200',
        height: '140',
        size: '58859',
        webp: 'http:\/\/media2.giphy.com\/media\/11fucLQCTOdvBS\/200w_d.webp',
        webp_size: '27096',
      },
      fixed_height_small: {
        url: 'https:\/\/media2.giphy.com\/media\/11fucLQCTOdvBS\/100.gif',
        width: '143',
        height: '100',
        size: '74643',
        mp4: 'http:\/\/media2.giphy.com\/media\/11fucLQCTOdvBS\/100.mp4',
        mp4_size: '8293',
        webp: 'http:\/\/media2.giphy.com\/media\/11fucLQCTOdvBS\/100.webp',
        webp_size: '42234',
      },
      fixed_height_small_still: {
        url: 'https:\/\/media2.giphy.com\/media\/11fucLQCTOdvBS\/100_s.gif',
        width: '143',
        height: '100',
      },
      fixed_width_small: {
        url: 'https:\/\/media2.giphy.com\/media\/11fucLQCTOdvBS\/100w.gif',
        width: '100',
        height: '70',
        size: '39519',
        mp4: 'http:\/\/media2.giphy.com\/media\/11fucLQCTOdvBS\/100w.mp4',
        mp4_size: '5870',
        webp: 'http:\/\/media2.giphy.com\/media\/11fucLQCTOdvBS\/100w.webp',
        webp_size: '26350',
      },
      fixed_width_small_still: {
        url: 'https:\/\/media2.giphy.com\/media\/11fucLQCTOdvBS\/100w_s.gif',
        width: '100',
        height: '70',
      },
      downsized: {
        url: 'http:\/\/media3.giphy.com\/media\/11fucLQCTOdvBS\/giphy-downsized.gif',
        width: '500',
        height: '350',
        size: '715304',
      },
      downsized_still: {
        url: 'http:\/\/media3.giphy.com\/media\/11fucLQCTOdvBS\/giphy-downsized_s.gif',
        width: '500',
        height: '350',
        size: '68612',
      },
      downsized_large: {
        url: 'https:\/\/media2.giphy.com\/media\/11fucLQCTOdvBS\/giphy.gif',
        width: '500',
        height: '350',
        size: '715304',
      },
      downsized_medium: {
        url: 'http:\/\/media2.giphy.com\/media\/11fucLQCTOdvBS\/giphy.gif',
        width: '500',
        height: '350',
        size: '715304',
      },
      original: {
        url: 'https:\/\/media2.giphy.com\/media\/11fucLQCTOdvBS\/giphy.gif',
        width: '500',
        height: '350',
        size: '715304',
        frames: '14',
        mp4: 'http:\/\/media2.giphy.com\/media\/11fucLQCTOdvBS\/giphy.mp4',
        mp4_size: '37442',
        webp: 'http:\/\/media2.giphy.com\/media\/11fucLQCTOdvBS\/giphy.webp',
        webp_size: '223628',
      },
      original_still: {
        url: 'https:\/\/media2.giphy.com\/media\/11fucLQCTOdvBS\/giphy_s.gif',
        width: '500',
        height: '350',
      },
      looping: {
        mp4: 'https:\/\/media.giphy.com\/media\/11fucLQCTOdvBS\/giphy-loop.mp4',
      },
      original_mp4: {
        mp4: 'http:\/\/media3.giphy.com\/media\/11fucLQCTOdvBS\/giphy.mp4',
        mp4_size: '37442',
        width: '480',
        height: '336',
      },
      preview: {
        mp4: 'http:\/\/media3.giphy.com\/media\/11fucLQCTOdvBS\/giphy-preview.mp4',
        mp4_size: '40908',
        width: '450',
        height: '314',
      },
      downsized_small: {
        mp4: 'http:\/\/media3.giphy.com\/media\/11fucLQCTOdvBS\/giphy-downsized-small.mp4',
        mp4_size: '53440',
      },
      preview_gif: {
        url: 'http:\/\/media3.giphy.com\/media\/11fucLQCTOdvBS\/giphy-preview.gif',
        width: '163',
        height: '114',
        size: '47439',
      },
    },
  }, {
    type: 'gif',
    id: 'yFQ0ywscgobJK',
    slug: 'facepalm-yFQ0ywscgobJK',
    url: 'http:\/\/giphy.com\/gifs\/facepalm-yFQ0ywscgobJK',
    bitly_gif_url: 'http:\/\/gph.is\/1LKJYOO',
    bitly_url: 'http:\/\/gph.is\/1LKJYOO',
    embed_url: 'http:\/\/giphy.com\/embed\/yFQ0ywscgobJK',
    username: '',
    source: 'http:\/\/www.reddit.com\/r\/gifs\/comments\/3ookcr\/double_facepalm\/',
    rating: 'pg',
    content_url: '',
    source_tld: 'www.reddit.com',
    source_post_url: 'http:\/\/www.reddit.com\/r\/gifs\/comments\/3ookcr\/double_facepalm\/',
    is_indexable: 0,
    import_datetime: '2015-10-14 04:32:38',
    trending_datetime: '2016-05-29 11:15:01',
    images: {
      fixed_height: {
        url: 'http:\/\/media3.giphy.com\/media\/yFQ0ywscgobJK\/200.gif',
        width: '166',
        height: '200',
        size: '1791106',
        mp4: 'http:\/\/media3.giphy.com\/media\/yFQ0ywscgobJK\/200.mp4',
        mp4_size: '88285',
        webp: 'http:\/\/media3.giphy.com\/media\/yFQ0ywscgobJK\/200.webp',
        webp_size: '944258',
      },
      fixed_height_still: {
        url: 'http:\/\/media3.giphy.com\/media\/yFQ0ywscgobJK\/200_s.gif',
        width: '166',
        height: '200',
      },
      fixed_height_downsampled: {
        url: 'http:\/\/media3.giphy.com\/media\/yFQ0ywscgobJK\/200_d.gif',
        width: '166',
        height: '200',
        size: '94130',
        webp: 'http:\/\/media3.giphy.com\/media\/yFQ0ywscgobJK\/200_d.webp',
        webp_size: '43804',
      },
      fixed_width: {
        url: 'http:\/\/media3.giphy.com\/media\/yFQ0ywscgobJK\/200w.gif',
        width: '200',
        height: '241',
        size: '2484648',
        mp4: 'http:\/\/media3.giphy.com\/media\/yFQ0ywscgobJK\/200w.mp4',
        mp4_size: '112807',
        webp: 'http:\/\/media3.giphy.com\/media\/yFQ0ywscgobJK\/200w.webp',
        webp_size: '1412918',
      },
      fixed_width_still: {
        url: 'http:\/\/media3.giphy.com\/media\/yFQ0ywscgobJK\/200w_s.gif',
        width: '200',
        height: '241',
      },
      fixed_width_downsampled: {
        url: 'http:\/\/media3.giphy.com\/media\/yFQ0ywscgobJK\/200w_d.gif',
        width: '200',
        height: '241',
        size: '134124',
        webp: 'http:\/\/media3.giphy.com\/media\/yFQ0ywscgobJK\/200w_d.webp',
        webp_size: '66392',
      },
      fixed_height_small: {
        url: 'http:\/\/media3.giphy.com\/media\/yFQ0ywscgobJK\/100.gif',
        width: '83',
        height: '100',
        size: '542356',
        mp4: 'http:\/\/media3.giphy.com\/media\/yFQ0ywscgobJK\/100.mp4',
        mp4_size: '35988',
        webp: 'http:\/\/media3.giphy.com\/media\/yFQ0ywscgobJK\/100.webp',
        webp_size: '307166',
      },
      fixed_height_small_still: {
        url: 'http:\/\/media3.giphy.com\/media\/yFQ0ywscgobJK\/100_s.gif',
        width: '83',
        height: '100',
      },
      fixed_width_small: {
        url: 'http:\/\/media3.giphy.com\/media\/yFQ0ywscgobJK\/100w.gif',
        width: '100',
        height: '121',
        size: '745073',
        mp4: 'http:\/\/media3.giphy.com\/media\/yFQ0ywscgobJK\/100w.mp4',
        mp4_size: '44066',
        webp: 'http:\/\/media3.giphy.com\/media\/yFQ0ywscgobJK\/100w.webp',
        webp_size: '393428',
      },
      fixed_width_small_still: {
        url: 'http:\/\/media3.giphy.com\/media\/yFQ0ywscgobJK\/100w_s.gif',
        width: '100',
        height: '121',
      },
      downsized: {
        url: 'http:\/\/media1.giphy.com\/media\/yFQ0ywscgobJK\/giphy-downsized.gif',
        width: '243',
        height: '293',
        size: '1060108',
      },
      downsized_still: {
        url: 'http:\/\/media1.giphy.com\/media\/yFQ0ywscgobJK\/giphy-downsized_s.gif',
        width: '243',
        height: '293',
        size: '19710',
      },
      downsized_large: {
        url: 'http:\/\/media3.giphy.com\/media\/yFQ0ywscgobJK\/giphy.gif',
        width: '243',
        height: '293',
        size: '2086050',
      },
      downsized_medium: {
        url: 'http:\/\/media3.giphy.com\/media\/yFQ0ywscgobJK\/giphy.gif',
        width: '243',
        height: '293',
        size: '2086050',
      },
      original: {
        url: 'http:\/\/media3.giphy.com\/media\/yFQ0ywscgobJK\/giphy.gif',
        width: '243',
        height: '293',
        size: '2086050',
        frames: '130',
        mp4: 'http:\/\/media3.giphy.com\/media\/yFQ0ywscgobJK\/giphy.mp4',
        mp4_size: '934549',
        webp: 'http:\/\/media3.giphy.com\/media\/yFQ0ywscgobJK\/giphy.webp',
        webp_size: '2636154',
      },
      original_still: {
        url: 'http:\/\/media3.giphy.com\/media\/yFQ0ywscgobJK\/giphy_s.gif',
        width: '243',
        height: '293',
      },
      looping: {
        mp4: 'http:\/\/media.giphy.com\/media\/yFQ0ywscgobJK\/giphy-loop.mp4',
      },
      original_mp4: {
        mp4: 'http:\/\/media1.giphy.com\/media\/yFQ0ywscgobJK\/giphy.mp4',
        mp4_size: '934549',
        width: '480',
        height: '578',
      },
      preview: {
        mp4: 'http:\/\/media1.giphy.com\/media\/yFQ0ywscgobJK\/giphy-preview.mp4',
        mp4_size: '20909',
        width: '192',
        height: '232',
      },
      downsized_small: {
        mp4: 'http:\/\/media1.giphy.com\/media\/yFQ0ywscgobJK\/giphy-downsized-small.mp4',
        mp4_size: '141919',
      },
      preview_gif: {
        url: 'http:\/\/media1.giphy.com\/media\/yFQ0ywscgobJK\/giphy-preview.gif',
        width: '91',
        height: '110',
        size: '49052',
      },
    },
  }, {
    type: 'gif',
    id: '3oEjI0Jort6dqkW7Ty',
    slug: 'originals-animation-logo-kittens-3oEjI0Jort6dqkW7Ty',
    url: 'http:\/\/giphy.com\/gifs\/originals-animation-logo-kittens-3oEjI0Jort6dqkW7Ty',
    bitly_gif_url: 'http:\/\/gph.is\/1UcBWXP',
    bitly_url: 'http:\/\/gph.is\/1UcBWXP',
    embed_url: 'http:\/\/giphy.com\/embed\/3oEjI0Jort6dqkW7Ty',
    username: 'originals',
    source: 'giphy.com',
    rating: 'g',
    content_url: '',
    user: {
      avatar_url: 'https:\/\/media2.giphy.com\/avatars\/originals\/jbZknXnoVxIt.jpg',
      banner_url: '',
      profile_url: 'https:\/\/giphy.com\/originals\/',
      username: 'originals',
      display_name: 'GIPHY Originals',
    },
    source_tld: '',
    source_post_url: 'giphy.com',
    is_indexable: 1,
    import_datetime: '2016-06-07 16:20:56',
    trending_datetime: '2017-01-27 23:45:01',
    images: {
      fixed_height: {
        url: 'http:\/\/media2.giphy.com\/media\/3oEjI0Jort6dqkW7Ty\/200.gif',
        width: '356',
        height: '200',
        size: '1634456',
        mp4: 'http:\/\/media2.giphy.com\/media\/3oEjI0Jort6dqkW7Ty\/200.mp4',
        mp4_size: '52345',
        webp: 'http:\/\/media2.giphy.com\/media\/3oEjI0Jort6dqkW7Ty\/200.webp',
        webp_size: '558710',
      },
      fixed_height_still: {
        url: 'http:\/\/media2.giphy.com\/media\/3oEjI0Jort6dqkW7Ty\/200_s.gif',
        width: '356',
        height: '200',
      },
      fixed_height_downsampled: {
        url: 'http:\/\/media2.giphy.com\/media\/3oEjI0Jort6dqkW7Ty\/200_d.gif',
        width: '356',
        height: '200',
        size: '63840',
        webp: 'http:\/\/media2.giphy.com\/media\/3oEjI0Jort6dqkW7Ty\/200_d.webp',
        webp_size: '21598',
      },
      fixed_width: {
        url: 'http:\/\/media2.giphy.com\/media\/3oEjI0Jort6dqkW7Ty\/200w.gif',
        width: '200',
        height: '113',
        size: '522829',
        mp4: 'http:\/\/media2.giphy.com\/media\/3oEjI0Jort6dqkW7Ty\/200w.mp4',
        mp4_size: '26589',
        webp: 'http:\/\/media2.giphy.com\/media\/3oEjI0Jort6dqkW7Ty\/200w.webp',
        webp_size: '256086',
      },
      fixed_width_still: {
        url: 'http:\/\/media2.giphy.com\/media\/3oEjI0Jort6dqkW7Ty\/200w_s.gif',
        width: '200',
        height: '113',
      },
      fixed_width_downsampled: {
        url: 'http:\/\/media2.giphy.com\/media\/3oEjI0Jort6dqkW7Ty\/200w_d.gif',
        width: '200',
        height: '113',
        size: '21953',
        webp: 'http:\/\/media2.giphy.com\/media\/3oEjI0Jort6dqkW7Ty\/200w_d.webp',
        webp_size: '10392',
      },
      fixed_height_small: {
        url: 'http:\/\/media2.giphy.com\/media\/3oEjI0Jort6dqkW7Ty\/100.gif',
        width: '178',
        height: '100',
        size: '451723',
        mp4: 'http:\/\/media2.giphy.com\/media\/3oEjI0Jort6dqkW7Ty\/100.mp4',
        mp4_size: '22729',
        webp: 'http:\/\/media2.giphy.com\/media\/3oEjI0Jort6dqkW7Ty\/100.webp',
        webp_size: '225164',
      },
      fixed_height_small_still: {
        url: 'http:\/\/media2.giphy.com\/media\/3oEjI0Jort6dqkW7Ty\/100_s.gif',
        width: '178',
        height: '100',
      },
      fixed_width_small: {
        url: 'http:\/\/media2.giphy.com\/media\/3oEjI0Jort6dqkW7Ty\/100w.gif',
        width: '100',
        height: '56',
        size: '138750',
        mp4: 'http:\/\/media2.giphy.com\/media\/3oEjI0Jort6dqkW7Ty\/100w.mp4',
        mp4_size: '13939',
        webp: 'http:\/\/media2.giphy.com\/media\/3oEjI0Jort6dqkW7Ty\/100w.webp',
        webp_size: '115074',
      },
      fixed_width_small_still: {
        url: 'http:\/\/media2.giphy.com\/media\/3oEjI0Jort6dqkW7Ty\/100w_s.gif',
        width: '100',
        height: '56',
      },
      downsized: {
        url: 'http:\/\/media.giphy.com\/media\/3oEjI0Jort6dqkW7Ty\/giphy-tumblr.gif',
        width: '500',
        height: '281',
        size: '1174654',
      },
      downsized_still: {
        url: 'http:\/\/media.giphy.com\/media\/3oEjI0Jort6dqkW7Ty\/giphy-tumblr_s.gif',
        width: '500',
        height: '281',
      },
      downsized_large: {
        url: 'http:\/\/media2.giphy.com\/media\/3oEjI0Jort6dqkW7Ty\/giphy-downsized-large.gif',
        width: '768',
        height: '432',
        size: '4917065',
      },
      downsized_medium: {
        url: 'http:\/\/media2.giphy.com\/media\/3oEjI0Jort6dqkW7Ty\/giphy-downsized-medium.gif',
        width: '768',
        height: '432',
        size: '4211315',
      },
      original: {
        url: 'http:\/\/media2.giphy.com\/media\/3oEjI0Jort6dqkW7Ty\/giphy.gif',
        width: '768',
        height: '432',
        size: '8471675',
        frames: '189',
        mp4: 'http:\/\/media2.giphy.com\/media\/3oEjI0Jort6dqkW7Ty\/giphy.mp4',
        mp4_size: '79271',
        webp: 'http:\/\/media2.giphy.com\/media\/3oEjI0Jort6dqkW7Ty\/giphy.webp',
        webp_size: '2528126',
      },
      original_still: {
        url: 'http:\/\/media2.giphy.com\/media\/3oEjI0Jort6dqkW7Ty\/giphy_s.gif',
        width: '768',
        height: '432',
      },
      looping: {
        mp4: 'http:\/\/media.giphy.com\/media\/3oEjI0Jort6dqkW7Ty\/giphy-loop.mp4',
      },
      preview: {
        mp4: 'http:\/\/media3.giphy.com\/media\/3oEjI0Jort6dqkW7Ty\/giphy-preview.mp4',
        mp4_size: '37719',
        width: '768',
        height: '432',
      },
      downsized_small: {
        mp4: 'http:\/\/media3.giphy.com\/media\/3oEjI0Jort6dqkW7Ty\/giphy-downsized-small.mp4',
        mp4_size: '174539',
      },
      hd: {
        mp4: 'http:\/\/media3.giphy.com\/media\/3oEjI0Jort6dqkW7Ty\/giphy-hd.mp4',
        mp4_size: '252856',
        width: '768',
        height: '432',
      },
      preview_gif: {
        url: 'http:\/\/media3.giphy.com\/media\/3oEjI0Jort6dqkW7Ty\/giphy-preview.gif',
        width: '258',
        height: '145',
        size: '48645',
      },
    },
  }, {
    type: 'gif',
    id: 'ueRllJW9XPUWs',
    slug: 'cat-creepy-ueRllJW9XPUWs',
    url: 'http:\/\/giphy.com\/gifs\/cat-creepy-ueRllJW9XPUWs',
    bitly_gif_url: 'http:\/\/gph.is\/XM03Aw',
    bitly_url: 'http:\/\/gph.is\/XM03Aw',
    embed_url: 'http:\/\/giphy.com\/embed\/ueRllJW9XPUWs',
    username: '',
    source: 'http:\/\/rebloggy.com\/post\/gif-cat-funny-gifs-mine-upload-comedy-kitten-gun-starscream-olan-rogers-balloons\/37739637295',
    rating: 'pg',
    content_url: '',
    source_tld: 'rebloggy.com',
    source_post_url: 'http:\/\/rebloggy.com\/post\/gif-cat-funny-gifs-mine-upload-comedy-kitten-gun-starscream-olan-rogers-balloons\/37739637295',
    is_indexable: 0,
    import_datetime: '2013-03-20 06:37:47',
    trending_datetime: '2017-02-12 12:00:01',
    images: {
      fixed_height: {
        url: 'http:\/\/media4.giphy.com\/media\/ueRllJW9XPUWs\/200.gif',
        width: '356',
        height: '200',
        size: '205443',
        mp4: 'http:\/\/media4.giphy.com\/media\/ueRllJW9XPUWs\/200.mp4',
        mp4_size: '14912',
        webp: 'http:\/\/media4.giphy.com\/media\/ueRllJW9XPUWs\/200.webp',
        webp_size: '217866',
      },
      fixed_height_still: {
        url: 'http:\/\/media4.giphy.com\/media\/ueRllJW9XPUWs\/200_s.gif',
        width: '356',
        height: '200',
      },
      fixed_height_downsampled: {
        url: 'http:\/\/media4.giphy.com\/media\/ueRllJW9XPUWs\/200_d.gif',
        width: '356',
        height: '200',
        size: '365941',
        webp: 'http:\/\/media4.giphy.com\/media\/ueRllJW9XPUWs\/200_d.webp',
        webp_size: '109858',
      },
      fixed_width: {
        url: 'http:\/\/media4.giphy.com\/media\/ueRllJW9XPUWs\/200w.gif',
        width: '200',
        height: '113',
        size: '88797',
        mp4: 'http:\/\/media4.giphy.com\/media\/ueRllJW9XPUWs\/200w.mp4',
        mp4_size: '17617',
        webp: 'http:\/\/media4.giphy.com\/media\/ueRllJW9XPUWs\/200w.webp',
        webp_size: '84330',
      },
      fixed_width_still: {
        url: 'http:\/\/media4.giphy.com\/media\/ueRllJW9XPUWs\/200w_s.gif',
        width: '200',
        height: '113',
      },
      fixed_width_downsampled: {
        url: 'http:\/\/media4.giphy.com\/media\/ueRllJW9XPUWs\/200w_d.gif',
        width: '200',
        height: '113',
        size: '131762',
        webp: 'http:\/\/media4.giphy.com\/media\/ueRllJW9XPUWs\/200w_d.webp',
        webp_size: '42568',
      },
      fixed_height_small: {
        url: 'http:\/\/media4.giphy.com\/media\/ueRllJW9XPUWs\/100.gif',
        width: '178',
        height: '100',
        size: '205443',
        mp4: 'http:\/\/media4.giphy.com\/media\/ueRllJW9XPUWs\/100.mp4',
        mp4_size: '60458',
        webp: 'http:\/\/media4.giphy.com\/media\/ueRllJW9XPUWs\/100.webp',
        webp_size: '60742',
      },
      fixed_height_small_still: {
        url: 'http:\/\/media4.giphy.com\/media\/ueRllJW9XPUWs\/100_s.gif',
        width: '178',
        height: '100',
      },
      fixed_width_small: {
        url: 'http:\/\/media4.giphy.com\/media\/ueRllJW9XPUWs\/100w.gif',
        width: '100',
        height: '56',
        size: '88797',
        mp4: 'http:\/\/media4.giphy.com\/media\/ueRllJW9XPUWs\/100w.mp4',
        mp4_size: '30172',
        webp: 'http:\/\/media4.giphy.com\/media\/ueRllJW9XPUWs\/100w.webp',
        webp_size: '25292',
      },
      fixed_width_small_still: {
        url: 'http:\/\/media4.giphy.com\/media\/ueRllJW9XPUWs\/100w_s.gif',
        width: '100',
        height: '56',
      },
      downsized: {
        url: 'http:\/\/media2.giphy.com\/media\/ueRllJW9XPUWs\/giphy-downsized.gif',
        width: '480',
        height: '270',
        size: '854085',
      },
      downsized_still: {
        url: 'http:\/\/media2.giphy.com\/media\/ueRllJW9XPUWs\/giphy-downsized_s.gif',
        width: '480',
        height: '270',
        size: '94666',
      },
      downsized_large: {
        url: 'http:\/\/media4.giphy.com\/media\/ueRllJW9XPUWs\/giphy.gif',
        width: '480',
        height: '270',
        size: '854085',
      },
      downsized_medium: {
        url: 'http:\/\/media4.giphy.com\/media\/ueRllJW9XPUWs\/giphy.gif',
        width: '480',
        height: '270',
        size: '854085',
      },
      original: {
        url: 'http:\/\/media4.giphy.com\/media\/ueRllJW9XPUWs\/giphy.gif',
        width: '480',
        height: '270',
        size: '854085',
        frames: '12',
        mp4: 'http:\/\/media4.giphy.com\/media\/ueRllJW9XPUWs\/giphy.mp4',
        mp4_size: '65775',
        webp: 'http:\/\/media4.giphy.com\/media\/ueRllJW9XPUWs\/giphy.webp',
        webp_size: '304706',
      },
      original_still: {
        url: 'http:\/\/media4.giphy.com\/media\/ueRllJW9XPUWs\/giphy_s.gif',
        width: '480',
        height: '270',
      },
      looping: {
        mp4: 'http:\/\/media.giphy.com\/media\/ueRllJW9XPUWs\/giphy-loop.mp4',
      },
      preview: {
        mp4: 'http:\/\/media2.giphy.com\/media\/ueRllJW9XPUWs\/giphy-preview.mp4',
        mp4_size: '43333',
        width: '398',
        height: '222',
      },
      downsized_small: {
        mp4: 'http:\/\/media2.giphy.com\/media\/ueRllJW9XPUWs\/giphy-downsized-small.mp4',
        mp4_size: '72477',
      },
      preview_gif: {
        url: 'http:\/\/media2.giphy.com\/media\/ueRllJW9XPUWs\/giphy-preview.gif',
        width: '119',
        height: '67',
        size: '46743',
      },
    },
  }, {
    type: 'gif',
    id: 'F69JmzpmSaffi',
    slug: 'cat-kitten-F69JmzpmSaffi',
    url: 'http:\/\/giphy.com\/gifs\/cat-kitten-F69JmzpmSaffi',
    bitly_gif_url: 'http:\/\/gph.is\/19mGa5t',
    bitly_url: 'http:\/\/gph.is\/19mGa5t',
    embed_url: 'http:\/\/giphy.com\/embed\/F69JmzpmSaffi',
    username: '',
    source: 'http:\/\/gifhell.com\/',
    rating: 'pg',
    content_url: '',
    source_tld: 'gifhell.com',
    source_post_url: 'http:\/\/gifhell.com\/',
    is_indexable: 0,
    import_datetime: '2013-09-05 16:09:51',
    trending_datetime: '2017-02-12 01:30:01',
    images: {
      fixed_height: {
        url: 'http:\/\/media1.giphy.com\/media\/F69JmzpmSaffi\/200.gif',
        width: '281',
        height: '200',
        size: '309958',
        mp4: 'http:\/\/media1.giphy.com\/media\/F69JmzpmSaffi\/200.mp4',
        mp4_size: '26370',
        webp: 'http:\/\/media1.giphy.com\/media\/F69JmzpmSaffi\/200.webp',
        webp_size: '475406',
      },
      fixed_height_still: {
        url: 'http:\/\/media1.giphy.com\/media\/F69JmzpmSaffi\/200_s.gif',
        width: '281',
        height: '200',
      },
      fixed_height_downsampled: {
        url: 'http:\/\/media1.giphy.com\/media\/F69JmzpmSaffi\/200_d.gif',
        width: '281',
        height: '200',
        size: '172933',
        webp: 'http:\/\/media1.giphy.com\/media\/F69JmzpmSaffi\/200_d.webp',
        webp_size: '50254',
      },
      fixed_width: {
        url: 'http:\/\/media1.giphy.com\/media\/F69JmzpmSaffi\/200w.gif',
        width: '200',
        height: '142',
        size: '180694',
        mp4: 'http:\/\/media1.giphy.com\/media\/F69JmzpmSaffi\/200w.mp4',
        mp4_size: '31316',
        webp: 'http:\/\/media1.giphy.com\/media\/F69JmzpmSaffi\/200w.webp',
        webp_size: '256004',
      },
      fixed_width_still: {
        url: 'http:\/\/media1.giphy.com\/media\/F69JmzpmSaffi\/200w_s.gif',
        width: '200',
        height: '142',
      },
      fixed_width_downsampled: {
        url: 'http:\/\/media1.giphy.com\/media\/F69JmzpmSaffi\/200w_d.gif',
        width: '200',
        height: '142',
        size: '108252',
        webp: 'http:\/\/media1.giphy.com\/media\/F69JmzpmSaffi\/200w_d.webp',
        webp_size: '27588',
      },
      fixed_height_small: {
        url: 'http:\/\/media1.giphy.com\/media\/F69JmzpmSaffi\/100.gif',
        width: '141',
        height: '100',
        size: '309958',
        mp4: 'http:\/\/media1.giphy.com\/media\/F69JmzpmSaffi\/100.mp4',
        mp4_size: '60478',
        webp: 'http:\/\/media1.giphy.com\/media\/F69JmzpmSaffi\/100.webp',
        webp_size: '125030',
      },
      fixed_height_small_still: {
        url: 'http:\/\/media1.giphy.com\/media\/F69JmzpmSaffi\/100_s.gif',
        width: '141',
        height: '100',
      },
      fixed_width_small: {
        url: 'http:\/\/media1.giphy.com\/media\/F69JmzpmSaffi\/100w.gif',
        width: '100',
        height: '71',
        size: '180694',
        mp4: 'http:\/\/media1.giphy.com\/media\/F69JmzpmSaffi\/100w.mp4',
        mp4_size: '48303',
        webp: 'http:\/\/media1.giphy.com\/media\/F69JmzpmSaffi\/100w.webp',
        webp_size: '80456',
      },
      fixed_width_small_still: {
        url: 'http:\/\/media1.giphy.com\/media\/F69JmzpmSaffi\/100w_s.gif',
        width: '100',
        height: '71',
      },
      downsized: {
        url: 'http:\/\/media1.giphy.com\/media\/F69JmzpmSaffi\/giphy.gif',
        width: '304',
        height: '216',
        size: '496400',
      },
      downsized_still: {
        url: 'http:\/\/media1.giphy.com\/media\/F69JmzpmSaffi\/giphy_s.gif',
        width: '304',
        height: '216',
      },
      downsized_large: {
        url: 'http:\/\/media1.giphy.com\/media\/F69JmzpmSaffi\/giphy.gif',
        width: '304',
        height: '216',
        size: '496400',
      },
      downsized_medium: {
        url: 'http:\/\/media1.giphy.com\/media\/F69JmzpmSaffi\/giphy.gif',
        width: '304',
        height: '216',
        size: '496400',
      },
      original: {
        url: 'http:\/\/media1.giphy.com\/media\/F69JmzpmSaffi\/giphy.gif',
        width: '304',
        height: '216',
        size: '496400',
        frames: '57',
        mp4: 'http:\/\/media1.giphy.com\/media\/F69JmzpmSaffi\/giphy.mp4',
        mp4_size: '101445',
        webp: 'http:\/\/media1.giphy.com\/media\/F69JmzpmSaffi\/giphy.webp',
        webp_size: '383640',
      },
      original_still: {
        url: 'http:\/\/media1.giphy.com\/media\/F69JmzpmSaffi\/giphy_s.gif',
        width: '304',
        height: '216',
      },
      looping: {
        mp4: 'http:\/\/media.giphy.com\/media\/F69JmzpmSaffi\/giphy-loop.mp4',
      },
      preview: {
        mp4: 'http:\/\/media3.giphy.com\/media\/F69JmzpmSaffi\/giphy-preview.mp4',
        mp4_size: '46670',
        width: '304',
        height: '216',
      },
      downsized_small: {
        mp4: 'http:\/\/media3.giphy.com\/media\/F69JmzpmSaffi\/giphy-downsized-small.mp4',
        mp4_size: '65665',
      },
      preview_gif: {
        url: 'http:\/\/media3.giphy.com\/media\/F69JmzpmSaffi\/giphy-preview.gif',
        width: '163',
        height: '116',
        size: '48330',
      },
    },
  }, {
    type: 'gif',
    id: 'wu29mJA7MXBzG',
    slug: 'cat-loop-relaxed-wu29mJA7MXBzG',
    url: 'http:\/\/giphy.com\/gifs\/cat-loop-relaxed-wu29mJA7MXBzG',
    bitly_gif_url: 'http:\/\/gph.is\/1a72aF1',
    bitly_url: 'http:\/\/gph.is\/1a72aF1',
    embed_url: 'http:\/\/giphy.com\/embed\/wu29mJA7MXBzG',
    username: 'sheepfilms',
    source: 'http:\/\/imgur.com\/gallery\/i31r2nv',
    rating: 'g',
    content_url: '',
    user: {
      avatar_url: 'https:\/\/media3.giphy.com\/avatars\/sheepfilms\/IRZqFGsPKx8f.png',
      banner_url: '',
      profile_url: 'https:\/\/giphy.com\/sheepfilms\/',
      username: 'sheepfilms',
      display_name: 'sheepfilms',
      twitter: '@sheepfilms',
    },
    source_tld: 'imgur.com',
    source_post_url: 'http:\/\/imgur.com\/gallery\/i31r2nv',
    is_indexable: 1,
    import_datetime: '2013-08-15 02:39:04',
    trending_datetime: '2017-02-12 01:00:01',
    images: {
      fixed_height: {
        url: 'http:\/\/media2.giphy.com\/media\/wu29mJA7MXBzG\/200.gif',
        width: '320',
        height: '200',
        size: '500684',
        mp4: 'http:\/\/media2.giphy.com\/media\/wu29mJA7MXBzG\/200.mp4',
        mp4_size: '61169',
        webp: 'http:\/\/media2.giphy.com\/media\/wu29mJA7MXBzG\/200.webp',
        webp_size: '402556',
      },
      fixed_height_still: {
        url: 'http:\/\/media2.giphy.com\/media\/wu29mJA7MXBzG\/200_s.gif',
        width: '320',
        height: '200',
      },
      fixed_height_downsampled: {
        url: 'http:\/\/media2.giphy.com\/media\/wu29mJA7MXBzG\/200_d.gif',
        width: '320',
        height: '200',
        size: '163318',
        webp: 'http:\/\/media2.giphy.com\/media\/wu29mJA7MXBzG\/200_d.webp',
        webp_size: '116068',
      },
      fixed_width: {
        url: 'http:\/\/media2.giphy.com\/media\/wu29mJA7MXBzG\/200w.gif',
        width: '200',
        height: '125',
        size: '213169',
        mp4: 'http:\/\/media2.giphy.com\/media\/wu29mJA7MXBzG\/200w.mp4',
        mp4_size: '31286',
        webp: 'http:\/\/media2.giphy.com\/media\/wu29mJA7MXBzG\/200w.webp',
        webp_size: '198008',
      },
      fixed_width_still: {
        url: 'http:\/\/media2.giphy.com\/media\/wu29mJA7MXBzG\/200w_s.gif',
        width: '200',
        height: '125',
      },
      fixed_width_downsampled: {
        url: 'http:\/\/media2.giphy.com\/media\/wu29mJA7MXBzG\/200w_d.gif',
        width: '200',
        height: '125',
        size: '70239',
        webp: 'http:\/\/media2.giphy.com\/media\/wu29mJA7MXBzG\/200w_d.webp',
        webp_size: '56962',
      },
      fixed_height_small: {
        url: 'http:\/\/media2.giphy.com\/media\/wu29mJA7MXBzG\/100.gif',
        width: '160',
        height: '100',
        size: '140974',
        mp4: 'http:\/\/media2.giphy.com\/media\/wu29mJA7MXBzG\/100.mp4',
        mp4_size: '21526',
        webp: 'http:\/\/media2.giphy.com\/media\/wu29mJA7MXBzG\/100.webp',
        webp_size: '130924',
      },
      fixed_height_small_still: {
        url: 'http:\/\/media2.giphy.com\/media\/wu29mJA7MXBzG\/100_s.gif',
        width: '160',
        height: '100',
      },
      fixed_width_small: {
        url: 'http:\/\/media2.giphy.com\/media\/wu29mJA7MXBzG\/100w.gif',
        width: '100',
        height: '63',
        size: '60510',
        mp4: 'http:\/\/media2.giphy.com\/media\/wu29mJA7MXBzG\/100w.mp4',
        mp4_size: '11929',
        webp: 'http:\/\/media2.giphy.com\/media\/wu29mJA7MXBzG\/100w.webp',
        webp_size: '60692',
      },
      fixed_width_small_still: {
        url: 'http:\/\/media2.giphy.com\/media\/wu29mJA7MXBzG\/100w_s.gif',
        width: '100',
        height: '63',
      },
      downsized: {
        url: 'http:\/\/media2.giphy.com\/media\/wu29mJA7MXBzG\/giphy.gif',
        width: '400',
        height: '250',
        size: '798316',
      },
      downsized_still: {
        url: 'http:\/\/media2.giphy.com\/media\/wu29mJA7MXBzG\/giphy_s.gif',
        width: '400',
        height: '250',
      },
      downsized_large: {
        url: 'http:\/\/media2.giphy.com\/media\/wu29mJA7MXBzG\/giphy.gif',
        width: '400',
        height: '250',
        size: '798316',
      },
      downsized_medium: {
        url: 'http:\/\/media2.giphy.com\/media\/wu29mJA7MXBzG\/giphy.gif',
        width: '400',
        height: '250',
        size: '798316',
      },
      original: {
        url: 'http:\/\/media2.giphy.com\/media\/wu29mJA7MXBzG\/giphy.gif',
        width: '400',
        height: '250',
        size: '798316',
        frames: '22',
        mp4: 'http:\/\/media2.giphy.com\/media\/wu29mJA7MXBzG\/giphy.mp4',
        mp4_size: '126422',
        webp: 'http:\/\/media2.giphy.com\/media\/wu29mJA7MXBzG\/giphy.webp',
        webp_size: '640000',
      },
      original_still: {
        url: 'http:\/\/media2.giphy.com\/media\/wu29mJA7MXBzG\/giphy_s.gif',
        width: '400',
        height: '250',
      },
      looping: {
        mp4: 'http:\/\/media.giphy.com\/media\/wu29mJA7MXBzG\/giphy-loop.mp4',
      },
      original_mp4: {
        mp4: 'http:\/\/media1.giphy.com\/media\/wu29mJA7MXBzG\/giphy.mp4',
        mp4_size: '126422',
        width: '480',
        height: '300',
      },
      preview: {
        mp4: 'http:\/\/media1.giphy.com\/media\/wu29mJA7MXBzG\/giphy-preview.mp4',
        mp4_size: '43856',
        width: '238',
        height: '148',
      },
      downsized_small: {
        mp4: 'http:\/\/media1.giphy.com\/media\/wu29mJA7MXBzG\/giphy-downsized-small.mp4',
        mp4_size: '139190',
      },
      preview_gif: {
        url: 'http:\/\/media1.giphy.com\/media\/wu29mJA7MXBzG\/giphy-preview.gif',
        width: '134',
        height: '84',
        size: '49200',
      },
    },
  }, {
    type: 'gif',
    id: 'xtGpIp4ixR6Gk',
    slug: 'animals-being-jerks-xtGpIp4ixR6Gk',
    url: 'http:\/\/giphy.com\/gifs\/animals-being-jerks-xtGpIp4ixR6Gk',
    bitly_gif_url: 'http:\/\/gph.is\/2cX0eUg',
    bitly_url: 'http:\/\/gph.is\/2cX0eUg',
    embed_url: 'http:\/\/giphy.com\/embed\/xtGpIp4ixR6Gk',
    username: '',
    source: 'http:\/\/atchuup.com\/animals-were-caught-being-complete-jerks\/',
    rating: 'g',
    content_url: '',
    source_tld: 'atchuup.com',
    source_post_url: 'http:\/\/atchuup.com\/animals-were-caught-being-complete-jerks\/',
    is_indexable: 0,
    import_datetime: '2016-09-17 16:27:03',
    trending_datetime: '2017-02-11 12:15:01',
    images: {
      fixed_height: {
       url: 'http:\/\/media2.giphy.com\/media\/xtGpIp4ixR6Gk\/200.gif',
       width: '224',
       height: '200',
       size: '2310912',
       mp4: 'http:\/\/media2.giphy.com\/media\/xtGpIp4ixR6Gk\/200.mp4',
       mp4_size: '122406',
       webp: 'http:\/\/media2.giphy.com\/media\/xtGpIp4ixR6Gk\/200.webp',
       webp_size: '678408',
     },
      fixed_height_still: {
       url: 'http:\/\/media2.giphy.com\/media\/xtGpIp4ixR6Gk\/200_s.gif',
       width: '224',
       height: '200',
     },
      fixed_height_downsampled: {
       url: 'http:\/\/media2.giphy.com\/media\/xtGpIp4ixR6Gk\/200_d.gif',
       width: '224',
       height: '200',
       size: '164873',
       webp: 'http:\/\/media2.giphy.com\/media\/xtGpIp4ixR6Gk\/200_d.webp',
       webp_size: '47618',
     },
      fixed_width: {
       url: 'http:\/\/media2.giphy.com\/media\/xtGpIp4ixR6Gk\/200w.gif',
       width: '200',
       height: '178',
       size: '1864433',
       mp4: 'http:\/\/media2.giphy.com\/media\/xtGpIp4ixR6Gk\/200w.mp4',
       mp4_size: '112817',
       webp: 'http:\/\/media2.giphy.com\/media\/xtGpIp4ixR6Gk\/200w.webp',
       webp_size: '581254',
     },
      fixed_width_still: {
       url: 'http:\/\/media2.giphy.com\/media\/xtGpIp4ixR6Gk\/200w_s.gif',
       width: '200',
       height: '178',
     },
      fixed_width_downsampled: {
       url: 'http:\/\/media2.giphy.com\/media\/xtGpIp4ixR6Gk\/200w_d.gif',
       width: '200',
       height: '178',
       size: '133112',
       webp: 'http:\/\/media2.giphy.com\/media\/xtGpIp4ixR6Gk\/200w_d.webp',
       webp_size: '41140',
     },
      fixed_height_small: {
       url: 'http:\/\/media2.giphy.com\/media\/xtGpIp4ixR6Gk\/100.gif',
       width: '112',
       height: '100',
       size: '665388',
       mp4: 'http:\/\/media2.giphy.com\/media\/xtGpIp4ixR6Gk\/100.mp4',
       mp4_size: '49012',
       webp: 'http:\/\/media2.giphy.com\/media\/xtGpIp4ixR6Gk\/100.webp',
       webp_size: '255030',
     },
      fixed_height_small_still: {
       url: 'http:\/\/media2.giphy.com\/media\/xtGpIp4ixR6Gk\/100_s.gif',
       width: '112',
       height: '100',
     },
      fixed_width_small: {
       url: 'http:\/\/media2.giphy.com\/media\/xtGpIp4ixR6Gk\/100w.gif',
       width: '100',
       height: '89',
       size: '545489',
       mp4: 'http:\/\/media2.giphy.com\/media\/xtGpIp4ixR6Gk\/100w.mp4',
       mp4_size: '45593',
       webp: 'http:\/\/media2.giphy.com\/media\/xtGpIp4ixR6Gk\/100w.webp',
       webp_size: '227764',
     },
      fixed_width_small_still: {
       url: 'http:\/\/media2.giphy.com\/media\/xtGpIp4ixR6Gk\/100w_s.gif',
       width: '100',
       height: '89',
     },
      downsized: {
       url: 'http:\/\/media.giphy.com\/media\/xtGpIp4ixR6Gk\/giphy-tumblr.gif',
       width: '250',
       height: '223',
       size: '1022440',
     },
      downsized_still: {
       url: 'http:\/\/media.giphy.com\/media\/xtGpIp4ixR6Gk\/giphy-tumblr_s.gif',
       width: '250',
       height: '223',
     },
      downsized_large: {
       url: 'http:\/\/media2.giphy.com\/media\/xtGpIp4ixR6Gk\/giphy-downsized-large.gif',
       width: '400',
       height: '356',
       size: '7020570',
     },
      downsized_medium: {
       url: 'http:\/\/media2.giphy.com\/media\/xtGpIp4ixR6Gk\/giphy-downsized-medium.gif',
       width: '280',
       height: '249',
       size: '3200341',
     },
      original: {
       url: 'http:\/\/media2.giphy.com\/media\/xtGpIp4ixR6Gk\/giphy.gif',
       width: '500',
       height: '446',
       size: '10808899',
       frames: '87',
       mp4: 'http:\/\/media2.giphy.com\/media\/xtGpIp4ixR6Gk\/giphy.mp4',
       mp4_size: '452514',
       webp: 'http:\/\/media2.giphy.com\/media\/xtGpIp4ixR6Gk\/giphy.webp',
       webp_size: '2962650',
     },
      original_still: {
       url: 'http:\/\/media2.giphy.com\/media\/xtGpIp4ixR6Gk\/giphy_s.gif',
       width: '500',
       height: '446',
     },
      looping: {
       mp4: 'http:\/\/media.giphy.com\/media\/xtGpIp4ixR6Gk\/giphy-loop.mp4',
     },
      preview: {
       mp4: 'http:\/\/media3.giphy.com\/media\/xtGpIp4ixR6Gk\/giphy-preview.mp4',
       mp4_size: '41627',
       width: '232',
       height: '206',
     },
      downsized_small: {
       mp4: 'http:\/\/media3.giphy.com\/media\/xtGpIp4ixR6Gk\/giphy-downsized-small.mp4',
       mp4_size: '180671',
     },
      preview_gif: {
       url: 'http:\/\/media3.giphy.com\/media\/xtGpIp4ixR6Gk\/giphy-preview.gif',
       width: '95',
       height: '85',
       size: '47939',
     },
    },
  }, {
    type: 'gif',
    id: 'KKKR0ZwHAzUsg',
    slug: 'powerrangers-cat-90s-KKKR0ZwHAzUsg',
    url: 'http:\/\/giphy.com\/gifs\/powerrangers-cat-90s-KKKR0ZwHAzUsg',
    bitly_gif_url: 'http:\/\/gph.is\/2jaL1AS',
    bitly_url: 'http:\/\/gph.is\/2jaL1AS',
    embed_url: 'http:\/\/giphy.com\/embed\/KKKR0ZwHAzUsg',
    username: 'powerrangers',
    source: 'http:\/\/www.youtube.com\/watch?v=mWKeZMIZP84',
    rating: 'g',
    content_url: '',
    user: {
     avatar_url: 'https:\/\/media4.giphy.com\/avatars\/powerrangers\/M4JhlAlviJrG.jpg',
     banner_url: 'https:\/\/media4.giphy.com\/headers\/powerrangers\/QdGbLwLawjda.jpg',
     profile_url: 'https:\/\/giphy.com\/powerrangers\/',
     username: 'powerrangers',
     display_name: 'Power Rangers',
     twitter: '@powerrangers',
   },
    source_tld: 'www.youtube.com',
    source_post_url: 'http:\/\/www.youtube.com\/watch?v=mWKeZMIZP84',
    is_indexable: 0,
    import_datetime: '2017-01-24 18:26:44',
    trending_datetime: '2017-02-10 23:00:01',
    images: {
     fixed_height: {
       url: 'http:\/\/media0.giphy.com\/media\/KKKR0ZwHAzUsg\/200.gif',
       width: '356',
       height: '200',
       size: '1657685',
       mp4: 'http:\/\/media0.giphy.com\/media\/KKKR0ZwHAzUsg\/200.mp4',
       mp4_size: '111939',
       webp: 'http:\/\/media0.giphy.com\/media\/KKKR0ZwHAzUsg\/200.webp',
       webp_size: '547354',
     },
     fixed_height_still: {
       url: 'http:\/\/media0.giphy.com\/media\/KKKR0ZwHAzUsg\/200_s.gif',
       width: '356',
       height: '200',
       size: '45700',
     },
     fixed_height_downsampled: {
       url: 'http:\/\/media0.giphy.com\/media\/KKKR0ZwHAzUsg\/200_d.gif',
       width: '356',
       height: '200',
       size: '264756',
       webp: 'http:\/\/media0.giphy.com\/media\/KKKR0ZwHAzUsg\/200_d.webp',
       webp_size: '73300',
     },
     fixed_width: {
       url: 'http:\/\/media0.giphy.com\/media\/KKKR0ZwHAzUsg\/200w.gif',
       width: '200',
       height: '113',
       size: '564193',
       mp4: 'http:\/\/media0.giphy.com\/media\/KKKR0ZwHAzUsg\/200w.mp4',
       mp4_size: '43833',
       webp: 'http:\/\/media0.giphy.com\/media\/KKKR0ZwHAzUsg\/200w.webp',
       webp_size: '239344',
     },
     fixed_width_still: {
       url: 'http:\/\/media0.giphy.com\/media\/KKKR0ZwHAzUsg\/200w_s.gif',
       width: '200',
       height: '113',
       size: '16922',
     },
     fixed_width_downsampled: {
       url: 'http:\/\/media0.giphy.com\/media\/KKKR0ZwHAzUsg\/200w_d.gif',
       width: '200',
       height: '113',
       size: '95675',
       webp: 'http:\/\/media0.giphy.com\/media\/KKKR0ZwHAzUsg\/200w_d.webp',
       webp_size: '31986',
     },
     fixed_height_small: {
       url: 'http:\/\/media0.giphy.com\/media\/KKKR0ZwHAzUsg\/100.gif',
       width: '178',
       height: '100',
       size: '476412',
       mp4: 'http:\/\/media0.giphy.com\/media\/KKKR0ZwHAzUsg\/100.mp4',
       mp4_size: '40940',
       webp: 'http:\/\/media0.giphy.com\/media\/KKKR0ZwHAzUsg\/100.webp',
       webp_size: '199198',
     },
     fixed_height_small_still: {
       url: 'http:\/\/media0.giphy.com\/media\/KKKR0ZwHAzUsg\/100_s.gif',
       width: '178',
       height: '100',
       size: '13811',
     },
     fixed_width_small: {
       url: 'http:\/\/media0.giphy.com\/media\/KKKR0ZwHAzUsg\/100w.gif',
       width: '100',
       height: '57',
       size: '164146',
       mp4: 'http:\/\/media0.giphy.com\/media\/KKKR0ZwHAzUsg\/100w.mp4',
       mp4_size: '17293',
       webp: 'http:\/\/media0.giphy.com\/media\/KKKR0ZwHAzUsg\/100w.webp',
       webp_size: '84246',
     },
     fixed_width_small_still: {
       url: 'http:\/\/media0.giphy.com\/media\/KKKR0ZwHAzUsg\/100w_s.gif',
       width: '100',
       height: '57',
       size: '5594',
     },
     downsized: {
       url: 'http:\/\/media0.giphy.com\/media\/KKKR0ZwHAzUsg\/giphy-downsized.gif',
       width: '250',
       height: '140',
       size: '847839',
     },
     downsized_still: {
       url: 'http:\/\/media0.giphy.com\/media\/KKKR0ZwHAzUsg\/giphy-downsized_s.gif',
       width: '250',
       height: '140',
       size: '24393',
     },
     downsized_large: {
       url: 'http:\/\/media0.giphy.com\/media\/KKKR0ZwHAzUsg\/giphy.gif',
       width: '480',
       height: '270',
       size: '2930904',
     },
     downsized_medium: {
       url: 'http:\/\/media0.giphy.com\/media\/KKKR0ZwHAzUsg\/giphy.gif',
       width: '480',
       height: '270',
       size: '2930904',
     },
     original: {
       url: 'http:\/\/media0.giphy.com\/media\/KKKR0ZwHAzUsg\/giphy.gif',
       width: '480',
       height: '270',
       size: '2930904',
       frames: '45',
       mp4: 'http:\/\/media0.giphy.com\/media\/KKKR0ZwHAzUsg\/giphy.mp4',
       mp4_size: '226625',
       webp: 'http:\/\/media0.giphy.com\/media\/KKKR0ZwHAzUsg\/giphy.webp',
       webp_size: '925348',
       hash: 'e2b5ce1aadcb8962712b0e7506f3cae2',
     },
     original_still: {
       url: 'http:\/\/media0.giphy.com\/media\/KKKR0ZwHAzUsg\/giphy_s.gif',
       width: '480',
       height: '270',
       size: '79046',
     },
     looping: {
       mp4: 'http:\/\/media0.giphy.com\/media\/KKKR0ZwHAzUsg\/giphy-loop.mp4',
       mp4_size: '1157575',
     },
     original_mp4: {
       mp4: 'http:\/\/media0.giphy.com\/media\/KKKR0ZwHAzUsg\/giphy.mp4',
       mp4_size: '226625',
       width: '480',
       height: '270',
     },
     preview: {
       mp4: 'http:\/\/media0.giphy.com\/media\/KKKR0ZwHAzUsg\/giphy-preview.mp4',
       mp4_size: '36535',
       width: '282',
       height: '158',
     },
     downsized_small: {
       mp4: 'http:\/\/media0.giphy.com\/media\/KKKR0ZwHAzUsg\/giphy-downsized-small.mp4',
       mp4_size: '157982',
     },
     preview_gif: {
       url: 'http:\/\/media0.giphy.com\/media\/KKKR0ZwHAzUsg\/giphy-preview.gif',
       width: '123',
       height: '69',
       size: '49070',
     },
   },
  }, {
   type: 'gif',
   id: 'WJOq6yKop0A1y',
   slug: 'love-cat-cute-WJOq6yKop0A1y',
   url: 'http:\/\/giphy.com\/gifs\/love-cat-cute-WJOq6yKop0A1y',
   bitly_gif_url: 'http:\/\/gph.is\/2fLnAg1',
   bitly_url: 'http:\/\/gph.is\/2fLnAg1',
   embed_url: 'http:\/\/giphy.com\/embed\/WJOq6yKop0A1y',
   username: '',
   source: 'https:\/\/www.reddit.com\/r\/gifs\/comments\/5fpwqs\/cat_mother_love_is_so_cute\/',
   rating: 'g',
   content_url: '',
   source_tld: 'www.reddit.com',
   source_post_url: 'https:\/\/www.reddit.com\/r\/gifs\/comments\/5fpwqs\/cat_mother_love_is_so_cute\/',
   is_indexable: 0,
   import_datetime: '2016-11-30 14:38:54',
   trending_datetime: '2017-01-28 06:30:01',
   images: {
     fixed_height: {
       url: 'http:\/\/media3.giphy.com\/media\/WJOq6yKop0A1y\/200.gif',
       width: '201',
       height: '200',
       size: '661107',
       mp4: 'http:\/\/media3.giphy.com\/media\/WJOq6yKop0A1y\/200.mp4',
       mp4_size: '73104',
       webp: 'http:\/\/media3.giphy.com\/media\/WJOq6yKop0A1y\/200.webp',
       webp_size: '402530',
     },
     fixed_height_still: {
       url: 'http:\/\/media3.giphy.com\/media\/WJOq6yKop0A1y\/200_s.gif',
       width: '201',
       height: '200',
       size: '19376',
     },
     fixed_height_downsampled: {
       url: 'http:\/\/media3.giphy.com\/media\/WJOq6yKop0A1y\/200_d.gif',
       width: '201',
       height: '200',
       size: '111666',
       webp: 'http:\/\/media3.giphy.com\/media\/WJOq6yKop0A1y\/200_d.webp',
       webp_size: '65688',
     },
     fixed_width: {
       url: 'http:\/\/media3.giphy.com\/media\/WJOq6yKop0A1y\/200w.gif',
       width: '200',
       height: '199',
       size: '658033',
       mp4: 'http:\/\/media3.giphy.com\/media\/WJOq6yKop0A1y\/200w.mp4',
       mp4_size: '72072',
       webp: 'http:\/\/media3.giphy.com\/media\/WJOq6yKop0A1y\/200w.webp',
       webp_size: '399108',
     },
     fixed_width_still: {
       url: 'http:\/\/media3.giphy.com\/media\/WJOq6yKop0A1y\/200w_s.gif',
       width: '200',
       height: '199',
       size: '19213',
     },
     fixed_width_downsampled: {
       url: 'http:\/\/media3.giphy.com\/media\/WJOq6yKop0A1y\/200w_d.gif',
       width: '200',
       height: '199',
       size: '111330',
       webp: 'http:\/\/media3.giphy.com\/media\/WJOq6yKop0A1y\/200w_d.webp',
       webp_size: '64958',
     },
     fixed_height_small: {
       url: 'http:\/\/media3.giphy.com\/media\/WJOq6yKop0A1y\/100.gif',
       width: '101',
       height: '100',
       size: '194942',
       mp4: 'http:\/\/media3.giphy.com\/media\/WJOq6yKop0A1y\/100.mp4',
       mp4_size: '30191',
       webp: 'http:\/\/media3.giphy.com\/media\/WJOq6yKop0A1y\/100.webp',
       webp_size: '143372',
     },
     fixed_height_small_still: {
       url: 'http:\/\/media3.giphy.com\/media\/WJOq6yKop0A1y\/100_s.gif',
       width: '101',
       height: '100',
       size: '6362',
     },
     fixed_width_small: {
       url: 'http:\/\/media3.giphy.com\/media\/WJOq6yKop0A1y\/100w.gif',
       width: '100',
       height: '100',
       size: '194578',
       mp4: 'http:\/\/media3.giphy.com\/media\/WJOq6yKop0A1y\/100w.mp4',
       mp4_size: '29981',
       webp: 'http:\/\/media3.giphy.com\/media\/WJOq6yKop0A1y\/100w.webp',
       webp_size: '140946',
     },
     fixed_width_small_still: {
       url: 'http:\/\/media3.giphy.com\/media\/WJOq6yKop0A1y\/100w_s.gif',
       width: '100',
       height: '100',
       size: '6353',
     },
     downsized: {
       url: 'http:\/\/media3.giphy.com\/media\/WJOq6yKop0A1y\/giphy-tumblr.gif',
       width: '250',
       height: '248',
       size: '1047137',
     },
     downsized_still: {
       url: 'http:\/\/media3.giphy.com\/media\/WJOq6yKop0A1y\/giphy-tumblr_s.gif',
       width: '250',
       height: '248',
       size: '29878',
     },
     downsized_large: {
       url: 'http:\/\/media3.giphy.com\/media\/WJOq6yKop0A1y\/giphy.gif',
       width: '350',
       height: '348',
       size: '2082757',
     },
     downsized_medium: {
       url: 'http:\/\/media3.giphy.com\/media\/WJOq6yKop0A1y\/giphy.gif',
       width: '350',
       height: '348',
       size: '2082757',
     },
     original: {
       url: 'http:\/\/media3.giphy.com\/media\/WJOq6yKop0A1y\/giphy.gif',
       width: '350',
       height: '348',
       size: '2082757',
       frames: '37',
       mp4: 'http:\/\/media0.giphy.com\/media\/WJOq6yKop0A1y\/giphy.mp4',
       mp4_size: '358392',
       webp: 'http:\/\/media3.giphy.com\/media\/WJOq6yKop0A1y\/giphy.webp',
       webp_size: '1135046',
       hash: '6bc48c33b53132e3d6b47f0d91659543',
     },
     original_still: {
       url: 'http:\/\/media3.giphy.com\/media\/WJOq6yKop0A1y\/giphy_s.gif',
       width: '350',
       height: '348',
       size: '58654',
     },
     looping: {
       mp4: 'http:\/\/media3.giphy.com\/media\/WJOq6yKop0A1y\/giphy-loop.mp4',
       mp4_size: '1458139',
     },
     original_mp4: {
       mp4: 'http:\/\/media3.giphy.com\/media\/WJOq6yKop0A1y\/giphy.mp4',
       mp4_size: '358392',
       width: '480',
       height: '476',
     },
     preview: {
       mp4: 'http:\/\/media3.giphy.com\/media\/WJOq6yKop0A1y\/giphy-preview.mp4',
       mp4_size: '49137',
       width: '180',
       height: '178',
     },
     downsized_small: {
       mp4: 'http:\/\/media3.giphy.com\/media\/WJOq6yKop0A1y\/giphy-downsized-small.mp4',
       mp4_size: '112019',
     },
     preview_gif: {
       url: 'http:\/\/media3.giphy.com\/media\/WJOq6yKop0A1y\/giphy-preview.gif',
       width: '101',
       height: '100',
       size: '49512',
     },
   },
 }, {
   type: 'gif',
   id: 'co9IXVaipZ0Yg',
   slug: 'co9IXVaipZ0Yg',
   url: 'http:\/\/giphy.com\/gifs\/co9IXVaipZ0Yg',
   bitly_gif_url: 'http:\/\/gph.is\/28ZV1ch',
   bitly_url: 'http:\/\/gph.is\/28ZV1ch',
   embed_url: 'http:\/\/giphy.com\/embed\/co9IXVaipZ0Yg',
   username: '',
   source: 'http:\/\/imgur.com\/gallery\/tL6yYBb',
   rating: 'g',
   content_url: '',
   source_tld: 'imgur.com',
   source_post_url: 'http:\/\/imgur.com\/gallery\/tL6yYBb',
   is_indexable: 0,
   import_datetime: '2016-06-28 04:21:50',
   trending_datetime: '2017-02-10 04:00:01',
   images: {
     fixed_height: {
       url: 'https:\/\/media3.giphy.com\/media\/co9IXVaipZ0Yg\/200.gif',
       width: '356',
       height: '200',
       size: '885649',
       mp4: 'https:\/\/media3.giphy.com\/media\/co9IXVaipZ0Yg\/200.mp4',
       mp4_size: '42694',
       webp: 'http:\/\/media3.giphy.com\/media\/co9IXVaipZ0Yg\/200.webp',
       webp_size: '355642',
     },
     fixed_height_still: {
       url: 'https:\/\/media3.giphy.com\/media\/co9IXVaipZ0Yg\/200_s.gif',
       width: '356',
       height: '200',
     },
     fixed_height_downsampled: {
       url: 'https:\/\/media3.giphy.com\/media\/co9IXVaipZ0Yg\/200_d.gif',
       width: '356',
       height: '200',
       size: '217689',
       webp: 'http:\/\/media3.giphy.com\/media\/co9IXVaipZ0Yg\/200_d.webp',
       webp_size: '86360',
     },
     fixed_width: {
       url: 'https:\/\/media3.giphy.com\/media\/co9IXVaipZ0Yg\/200w.gif',
       width: '200',
       height: '112',
       size: '351412',
       mp4: 'https:\/\/media3.giphy.com\/media\/co9IXVaipZ0Yg\/200w.mp4',
       mp4_size: '20188',
       webp: 'http:\/\/media3.giphy.com\/media\/co9IXVaipZ0Yg\/200w.webp',
       webp_size: '160650',
     },
     fixed_width_still: {
       url: 'https:\/\/media3.giphy.com\/media\/co9IXVaipZ0Yg\/200w_s.gif',
       width: '200',
       height: '112',
     },
     fixed_width_downsampled: {
       url: 'https:\/\/media3.giphy.com\/media\/co9IXVaipZ0Yg\/200w_d.gif',
       width: '200',
       height: '112',
       size: '79056',
       webp: 'http:\/\/media3.giphy.com\/media\/co9IXVaipZ0Yg\/200w_d.webp',
       webp_size: '32016',
     },
     fixed_height_small: {
       url: 'https:\/\/media3.giphy.com\/media\/co9IXVaipZ0Yg\/100.gif',
       width: '178',
       height: '100',
       size: '307808',
       mp4: 'http:\/\/media3.giphy.com\/media\/co9IXVaipZ0Yg\/100.mp4',
       mp4_size: '17635',
       webp: 'http:\/\/media3.giphy.com\/media\/co9IXVaipZ0Yg\/100.webp',
       webp_size: '142198',
     },
     fixed_height_small_still: {
       url: 'https:\/\/media3.giphy.com\/media\/co9IXVaipZ0Yg\/100_s.gif',
       width: '178',
       height: '100',
     },
     fixed_width_small: {
       url: 'https:\/\/media3.giphy.com\/media\/co9IXVaipZ0Yg\/100w.gif',
       width: '100',
       height: '56',
       size: '129326',
       mp4: 'http:\/\/media3.giphy.com\/media\/co9IXVaipZ0Yg\/100w.mp4',
       mp4_size: '9220',
       webp: 'http:\/\/media3.giphy.com\/media\/co9IXVaipZ0Yg\/100w.webp',
       webp_size: '64496',
     },
     fixed_width_small_still: {
       url: 'https:\/\/media3.giphy.com\/media\/co9IXVaipZ0Yg\/100w_s.gif',
       width: '100',
       height: '56',
     },
     downsized: {
       url: 'http:\/\/media4.giphy.com\/media\/co9IXVaipZ0Yg\/giphy-downsized.gif',
       width: '500',
       height: '281',
       size: '1047991',
     },
     downsized_still: {
       url: 'http:\/\/media4.giphy.com\/media\/co9IXVaipZ0Yg\/giphy-downsized_s.gif',
       width: '500',
       height: '281',
       size: '58963',
     },
     downsized_large: {
       url: 'https:\/\/media3.giphy.com\/media\/co9IXVaipZ0Yg\/giphy.gif',
       width: '500',
       height: '281',
       size: '1047991',
     },
     downsized_medium: {
       url: 'http:\/\/media3.giphy.com\/media\/co9IXVaipZ0Yg\/giphy.gif',
       width: '500',
       height: '281',
       size: '1047991',
     },
     original: {
       url: 'https:\/\/media3.giphy.com\/media\/co9IXVaipZ0Yg\/giphy.gif',
       width: '500',
       height: '281',
       size: '1047991',
       frames: '40',
       mp4: 'https:\/\/media3.giphy.com\/media\/co9IXVaipZ0Yg\/giphy.mp4',
       mp4_size: '73329',
       webp: 'http:\/\/media3.giphy.com\/media\/co9IXVaipZ0Yg\/giphy.webp',
       webp_size: '573576',
     },
     original_still: {
       url: 'https:\/\/media3.giphy.com\/media\/co9IXVaipZ0Yg\/giphy_s.gif',
       width: '500',
       height: '281',
     },
     looping: {
       mp4: 'https:\/\/media.giphy.com\/media\/co9IXVaipZ0Yg\/giphy-loop.mp4',
     },
     preview: {
       mp4: 'http:\/\/media4.giphy.com\/media\/co9IXVaipZ0Yg\/giphy-preview.mp4',
       mp4_size: '25646',
       width: '400',
       height: '224',
     },
     downsized_small: {
       mp4: 'http:\/\/media4.giphy.com\/media\/co9IXVaipZ0Yg\/giphy-downsized-small.mp4',
       mp4_size: '108610',
     },
     preview_gif: {
       url: 'http:\/\/media4.giphy.com\/media\/co9IXVaipZ0Yg\/giphy-preview.gif',
       width: '196',
       height: '110',
       size: '48784',
     },
   },
 }],
  meta: {
    status: 200,
    msg: 'OK',
    response_id: '58a3d623cc5fb9eb0de06861',
  },
  pagination: {
    total_count: 70669,
    count: 10,
    offset: 0,
  },
};
